apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-ds
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gitlab
  template:
    metadata:
      labels: 
        app: my-gitlab
    spec:
      volumes:
        - name: gitlab-persistent-config
          nfs:
            server: 172.16.93.247
            path: /mnt/data/k8s/gitlab/config   ## u01为nfs的共享目录
        - name: gitlab-persistent-logs
          nfs:
            server: 172.16.93.247
            path: /mnt/data/k8s/gitlab/log   ## u01为nfs的共享目录
        - name: gitlab-persistent-data
          nfs:
            server: 172.16.93.247
            path: /mnt/data/k8s/gitlab/data   ## u01为nfs的共享目录
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
          - name: http
            containerPort: 80
          - name: ssh
            containerPort: 22
        volumeMounts:
          - name: gitlab-persistent-config
            mountPath: /etc/gitlab
          - name: gitlab-persistent-logs
            mountPath: /var/log/gitlab
          - name: gitlab-persistent-data
            mountPath: /var/opt/gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: devops
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30001
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    app: my-gitlab
