from php:5.6.40-fpm-alpine
MAINTAINER justcy(https://github.com/justcy)
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update \ 
&& apk add --no-cache ca-certificates tzdata && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENV REQUER="gnu-libiconv libpng-dev libmcrypt-dev libmemcached-dev libxml2-dev rabbitmq-c-dev freetype-dev libjpeg-turbo-dev libpng-dev"
ENV ALPINE_TOOLS="libpng tzdata zlib-dev libxml2 $PHPIZE_DEPS"
ENV PHP_EXT="pdo_mysql bcmath  mysqli shmop soap sockets xmlrpc mcrypt zip"
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ $REQUER $ALPINE_TOOLS \
        && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ docker-php-ext-install -j$(nproc) gd \
	&& docker-php-ext-install $PHP_EXT \
	&& pecl install amqp-1.9.4 redis-4.3.0 memcached-2.2.0 memcache-2.2.7 mongodb-1.7.4 \
	&& docker-php-ext-enable amqp redis memcached memcache mongodb \
	&& apk del $ALPINE_TOOLS
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
